[package]
name = "s3s"
version = "0.1.4"
authors = ["Simon THOBY <git@nightmared.fr>"]
edition = "2018"

[dependencies]
futures = "0.3.8"
chrono = "0.4"
#rust-s3 = { version = "0.26.3", default-features = false, features = ["rustls-tls"] }
rust-s3 = { git = "https://github.com/durch/rust-s3", default-features = false, features = ["with-tokio", "tokio-rustls-tls"] }
clap = "2.33"
tokio = { version = "0.2.23", features = ["blocking", "macros", "fs"] }
md-5 = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
